uploads = []
generated = []

[[outputs]]
id = "YAamqQeYEkBvzxvrax44P"
uri = "file://LuciFeR0x0systeM.zip"
type = "unspecified"
title = "LuciFeR0x0systeM — ソースコード"

[[outputs]]
id = "sRSKXgwahlknlMs07jpn9"
uri = "file://LuciFeR0x0systeM-CUI.zip"
type = "unspecified"
title = "LuciFeR0x0systeM — CUI版（iSH対応）"

[[outputs]]
id = "_L4NOGIvcUmIJeUF7o0y5"
uri = "file://jssh-engine.zip"
type = "unspecified"
title = "jssh DAG Engine v2 — LuciFeR0x0systeM"

[[outputs]]
id = "tTnOvThKBzf9AdnzuDTbe"
uri = "file://jssh-engine-v2.zip"
type = "unspecified"
title = "jssh v2 — Ubuntu 24.04 完全版"
